### ISSUE TITLE
Ensure uniqueness in each generation

### ISSUE THREAD

**Issue by Dagger038** [david-kriz/find-the-phrase#1]
Considerations for creating more variety in each population:
  1. Ensure uniquesness in each generation (2 suggestions)
    a. If (newSpecies.isDuplicateInGeneration()): newSpecies = generateNewSpecies()
    b. If (newSpecies.isDuplicateInGeneration()): <randomly select a character and change it>

**Comment by david-kriz** [comment]
Check the recent commit, @Dagger038 and @tbcrawford. This should resolve both issues. If you're satisfied, @Dagger038, go ahead and close the issues.

**Comment by david-kriz** [comment]
Closing the issue.
