### ISSUE TITLE
Reorder function definitions to reflect the order of use

### ISSUE THREAD

**Issue by Dagger038** [david-kriz/find-the-phrase#2]
For readability, it would help to have the function definitions in Population.js ordered by when they are called. This will help with reviewing logistical errors should they arise.

**Comment by david-kriz** [comment]
Check the recent commit, @Dagger038 and @tbcrawford. This should resolve both issues. If you're satisfied, @Dagger038, go ahead and close the issues.

**Comment by david-kriz** [comment]
Closing issue.
